# Generated by Django 4.2 on 2023-05-08 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('points', models.FloatField(default=100)),
                ('voice', models.FileField(null=True, upload_to='recording/')),
                ('exercise_type', models.CharField(choices=[('choices', 'choices'), ('words', 'words'), ('voice', 'voice')], max_length=60)),
                ('answers', models.ManyToManyField(to='exercises.answerchoices')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeholder_type', models.CharField(choices=[('text', 'text'), ('image', 'image'), ('voice', 'voice')], max_length=100)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('text', models.TextField(null=True)),
                ('voice', models.FileField(null=True, upload_to='recording/')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.classroom')),
                ('exercises', models.ManyToManyField(to='exercises.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='content_choices',
            field=models.ManyToManyField(to='exercises.exercisechoices'),
        ),
    ]
